import type { HeatLevel, SpiceEntity, SpiceForm } from "./types";

function spice(
  partial: Omit<SpiceEntity, "traditionalUses" | "storage" | "shelfLife" | "origin"> & {
    traditionalUses?: string;
    storage?: string;
    shelfLife?: string;
    origin?: string;
  }
): SpiceEntity {
  return {
    origin: partial.origin ?? "India",
    traditionalUses:
      partial.traditionalUses ??
      "Used in Indian culinary and traditional household practices. This is not a medical claim.",
    storage: partial.storage ?? "Airtight container, cool and dark, away from moisture and strong light.",
    shelfLife: partial.shelfLife ?? "Whole spices typically keep flavour longer than ground spices; check best-before on the pack.",
    ...partial,
  };
}

const WP: SpiceForm[] = ["whole", "powder"];
const CHILLI: SpiceForm[] = ["whole", "flakes", "powder", "crushed"];
const SEED: SpiceForm[] = ["whole"];
const BLEND: SpiceForm[] = ["blend"];

export const SPICE_ENTITIES: SpiceEntity[] = [
  spice({
    id: "cumin",
    slug: "cumin",
    canonicalName: "Cumin",
    commonNames: ["Cumin seeds", "Jeera"],
    indianNames: ["Jeera", "Jeeru", "Jira"],
    hindiName: "जीरा",
    regionalNames: ["Jeera", "Jeerige", "Jeerakam"],
    sanskritName: "Jiraka",
    botanicalName: "Cuminum cyminum",
    botanicalFamily: "Apiaceae",
    shortDescription: "Warm, earthy seed spice used across Indian cooking, from tadka to biryani.",
    description:
      "Cumin (jeera) is a staple Indian spice. Whole seeds are tempered in hot oil; ground cumin seasons curries, raitas, and spice blends. Indian production is concentrated in western states, with Unjha in Gujarat a well-known cumin market.",
    growingRegions: ["Rajasthan", "Gujarat"],
    harvestSeason: "Winter harvest (typically February–March, depending on region and year)",
    processing: "Dried, cleaned; export lots may be machine cleaned or sortex cleaned.",
    flavourProfile: "Warm, earthy, nutty, slightly bitter",
    aromaProfile: "Strong, warm, penetrating",
    colour: "Greenish-brown seeds",
    heatLevel: "none",
    culinaryUses: ["Tadka", "Dal", "Biryani", "Curry", "Raita", "Spice blends"],
    category: "seeds",
    relatedSlugs: ["black-cumin", "caraway", "coriander", "fennel"],
    recipeSlugs: ["jeera-rice", "dal-tadka", "jeera-aloo"],
    aliases: ["jeera", "jeera seeds", "cumin seeds", "cuminum cyminum", "जीरा", "जैरा", "jeeru", "bulk cumin"],
    forms: ["whole", "powder", "roasted"],
    varieties: [
      { slug: "cumin", name: "Cumin Seeds" },
      { slug: "unjha-cumin", name: "Unjha Cumin", region: "Gujarat" },
    ],
    grades: ["premium", "standard", "machine-cleaned"],
    featured: true,
  }),
  spice({
    id: "black-cumin",
    slug: "black-cumin",
    canonicalName: "Black Cumin",
    commonNames: ["Kala jeera", "Shahi jeera"],
    indianNames: ["Kala jeera", "Shahi jeera"],
    hindiName: "काला जीरा",
    regionalNames: ["Shahi jeera"],
    botanicalName: "Bunium persicum",
    botanicalFamily: "Apiaceae",
    shortDescription: "Smaller, darker cumin relative used in Mughlai and Kashmiri cooking.",
    description:
      "Black cumin (kala/shahi jeera) is distinct from common cumin. It is used more sparingly in biryanis and rich gravies. Do not confuse with nigella (kalonji), which is a different spice.",
    growingRegions: ["Kashmir", "Himachal Pradesh"],
    flavourProfile: "Sweeter and more floral than common cumin",
    aromaProfile: "Delicate, warm",
    colour: "Dark brown to blackish seeds",
    heatLevel: "none",
    culinaryUses: ["Biryani", "Korma", "Kashmiri dishes"],
    category: "seeds",
    relatedSlugs: ["cumin", "nigella", "caraway"],
    recipeSlugs: ["biryani"],
    aliases: ["kala jeera", "shahi jeera", "black cumin", "bunium persicum", "काला जीरा"],
    forms: WP,
    varieties: [{ slug: "black-cumin", name: "Black Cumin / Kala Jeera" }],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "coriander",
    slug: "coriander",
    canonicalName: "Coriander",
    commonNames: ["Coriander seeds", "Dhania"],
    indianNames: ["Dhania", "Dhaniya"],
    hindiName: "धनिया",
    regionalNames: ["Kothimbir", "Kothamalli"],
    botanicalName: "Coriandrum sativum",
    botanicalFamily: "Apiaceae",
    shortDescription: "Citrusy seed spice, the backbone of many Indian masalas.",
    description:
      "Coriander seeds and coriander powder are used throughout Indian cooking. Gujarat and Rajasthan are important producing regions. Ground coriander is milder than whole toasted seeds.",
    growingRegions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    flavourProfile: "Citrus, warm, slightly sweet",
    aromaProfile: "Fresh, lemony when crushed",
    colour: "Straw to light brown",
    heatLevel: "none",
    culinaryUses: ["Curry", "Masala blends", "Pickle", "Vegetables"],
    category: "seeds",
    relatedSlugs: ["cumin", "fennel", "ajwain"],
    recipeSlugs: ["curry", "sabzi"],
    aliases: ["dhania", "dhaniya", "coriander seeds", "coriander powder", "धनिया", "coriandrum sativum"],
    forms: ["whole", "powder", "roasted"],
    varieties: [{ slug: "coriander", name: "Coriander Seeds" }],
    grades: ["premium", "standard", "machine-cleaned"],
    featured: true,
  }),
  spice({
    id: "turmeric",
    slug: "turmeric",
    canonicalName: "Turmeric",
    commonNames: ["Haldi", "Turmeric rhizome"],
    indianNames: ["Haldi", "Manjal", "Pasupu"],
    hindiName: "हल्दी",
    regionalNames: ["Halad", "Arishina", "Manjal"],
    sanskritName: "Haridra",
    botanicalName: "Curcuma longa",
    botanicalFamily: "Zingiberaceae",
    shortDescription: "Golden rhizome spice used for colour, aroma, and everyday Indian cooking.",
    description:
      "Turmeric is grown widely in India. Erode (Tamil Nadu) and parts of Andhra Pradesh, Telangana, Maharashtra, and Odisha are known production areas. Culinary turmeric is not the same as isolated curcumin extracts. Traditional household uses should not be presented as proven medical treatment.",
    growingRegions: ["Tamil Nadu", "Andhra Pradesh", "Telangana", "Maharashtra", "Odisha", "Karnataka"],
    flavourProfile: "Earthy, slightly bitter, warm",
    aromaProfile: "Musty, ginger-adjacent",
    colour: "Deep yellow-orange",
    heatLevel: "none",
    culinaryUses: ["Curry", "Dal", "Rice", "Pickle", "Mustard oil pickles"],
    category: "roots",
    relatedSlugs: ["ginger", "galangal"],
    recipeSlugs: ["dal", "curry"],
    aliases: ["haldi", "manjal", "pasupu", "curcuma longa", "हल्दी", "turmeric powder"],
    forms: ["whole", "powder"],
    varieties: [
      { slug: "turmeric", name: "Turmeric" },
      { slug: "alleppey-turmeric", name: "Alleppey Finger Turmeric", region: "Kerala" },
    ],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "black-pepper",
    slug: "black-pepper",
    canonicalName: "Black Pepper",
    commonNames: ["Peppercorns", "Kali mirch"],
    indianNames: ["Kali mirch", "Kurumulaku"],
    hindiName: "काली मिर्च",
    regionalNames: ["Kurumulaku", "Milagu"],
    botanicalName: "Piper nigrum",
    botanicalFamily: "Piperaceae",
    shortDescription: "Malabar’s historic berry spice — whole peppercorns and ground pepper.",
    description:
      "Black pepper is native to the Western Ghats. Kerala’s Malabar coast is historically associated with pepper trade. Grades such as garbled / ungarbled appear in Indian market reports and should be stored as distinct grades, not a single generic price.",
    growingRegions: ["Kerala", "Karnataka", "Tamil Nadu"],
    flavourProfile: "Pungent, woody, sharp heat",
    aromaProfile: "Piney, warm",
    colour: "Dark brown to black wrinkled berries",
    heatLevel: "medium",
    culinaryUses: ["Curry", "Meat", "Garam masala", "Rasam"],
    category: "whole-spices",
    relatedSlugs: ["long-pepper", "cubeb", "white-pepper"],
    recipeSlugs: ["rasam", "pepper-chicken"],
    aliases: ["kali mirch", "peppercorns", "malabar pepper", "piper nigrum", "काली मिर्च", "kurumulaku"],
    forms: WP,
    varieties: [
      { slug: "malabar-pepper", name: "Malabar Black Pepper", region: "Kerala" },
      { slug: "tellicherry-pepper", name: "Tellicherry Pepper", region: "Kerala" },
    ],
    grades: ["garbled", "ungarbled", "premium"],
    featured: true,
  }),
  spice({
    id: "green-cardamom",
    slug: "green-cardamom",
    canonicalName: "Green Cardamom",
    commonNames: ["Elaichi", "Small cardamom"],
    indianNames: ["Hari elaichi", "Elakkai"],
    hindiName: "हरी इलायची",
    regionalNames: ["Elakkai", "Yelakki"],
    botanicalName: "Elettaria cardamomum",
    botanicalFamily: "Zingiberaceae",
    shortDescription: "Aromatic green pods from the Western Ghats, used in sweets, tea, and biryani.",
    description:
      "Small cardamom from Kerala (including the Cardamom Hills / Idukki belt) and Karnataka is a flagship Indian spice. Alleppey green cardamom is a recognised regional association. Use culinary language only; do not invent health cures.",
    growingRegions: ["Kerala", "Karnataka", "Tamil Nadu"],
    flavourProfile: "Floral, eucalyptus-camphor, sweet-spicy",
    aromaProfile: "Intensely fragrant",
    colour: "Green pods",
    heatLevel: "none",
    culinaryUses: ["Biryani", "Tea", "Sweets", "Korma", "Garam masala"],
    category: "premium-spices",
    relatedSlugs: ["black-cardamom", "cinnamon"],
    recipeSlugs: ["chai", "biryani", "kheer"],
    aliases: ["elaichi", "hari elaichi", "elettaria cardamomum", "green cardamom", "हरी इलायची", "elakkai"],
    forms: ["whole", "powder"],
    varieties: [
      { slug: "green-cardamom", name: "Green Cardamom" },
      { slug: "alleppey-cardamom", name: "Alleppey Green Cardamom", region: "Kerala" },
    ],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "black-cardamom",
    slug: "black-cardamom",
    canonicalName: "Black Cardamom",
    commonNames: ["Badi elaichi", "Brown cardamom"],
    indianNames: ["Badi elaichi"],
    hindiName: "बड़ी इलायची",
    regionalNames: ["Bari elaichi"],
    botanicalName: "Amomum subulatum",
    botanicalFamily: "Zingiberaceae",
    shortDescription: "Smoky large cardamom used in savoury North Indian cooking.",
    description:
      "Black cardamom is dried with smoke and used in garam masala, meat curries, and pulao. It is not a substitute for green cardamom in sweets.",
    growingRegions: ["Sikkim", "West Bengal", "Northeast India"],
    flavourProfile: "Camphor, smoke, resin",
    aromaProfile: "Smoky, medicinal-camphor",
    colour: "Dark brown wrinkled pods",
    heatLevel: "none",
    culinaryUses: ["Meat curry", "Pulao", "Garam masala"],
    category: "whole-spices",
    relatedSlugs: ["green-cardamom"],
    recipeSlugs: ["rogan-josh", "pulao"],
    aliases: ["badi elaichi", "black cardamom", "amomum subulatum", "बड़ी इलायची"],
    forms: WP,
    varieties: [{ slug: "black-cardamom", name: "Black Cardamom" }],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "clove",
    slug: "clove",
    canonicalName: "Clove",
    commonNames: ["Laung", "Lavang"],
    indianNames: ["Laung", "Lavang"],
    hindiName: "लौंग",
    regionalNames: ["Grambu", "Lavanga"],
    botanicalName: "Syzygium aromaticum",
    botanicalFamily: "Myrtaceae",
    shortDescription: "Dried flower buds, strongly aromatic, used sparingly in Indian cooking.",
    description:
      "Cloves used in India include both domestic and traded lots. Kerala has a clove-growing tradition. Market prices should be stored with market, grade, and date.",
    growingRegions: ["Kerala", "Tamil Nadu", "Karnataka"],
    flavourProfile: "Sweet-pungent, warming",
    aromaProfile: "Eugenol-rich, piercing",
    colour: "Reddish-brown buds",
    heatLevel: "none",
    culinaryUses: ["Biryani", "Garam masala", "Tea masala", "Meat"],
    category: "whole-spices",
    relatedSlugs: ["cinnamon", "green-cardamom"],
    recipeSlugs: ["biryani", "chai"],
    aliases: ["laung", "lavang", "cloves", "syzygium aromaticum", "लौंग"],
    forms: WP,
    varieties: [{ slug: "clove", name: "Cloves" }],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "cinnamon",
    slug: "cinnamon",
    canonicalName: "Cinnamon",
    commonNames: ["True cinnamon", "Ceylon-type cinnamon"],
    indianNames: ["Dalchini (often used loosely)"],
    hindiName: "दालचीनी",
    regionalNames: ["Karuvapatta"],
    botanicalName: "Cinnamomum verum",
    botanicalFamily: "Lauraceae",
    shortDescription: "Delicate inner bark. Distinct from cassia, which is often sold as dalchini in India.",
    description:
      "In Indian retail, “dalchini” often means cassia. SpicyCorner keeps cinnamon (Cinnamomum verum) and cassia (Cinnamomum cassia / C. tamala-related trade names) as separate entities so labels stay accurate.",
    growingRegions: ["Kerala"],
    flavourProfile: "Sweet, delicate, citrus-woody",
    aromaProfile: "Soft, sweet bark",
    colour: "Pale tan quills",
    heatLevel: "none",
    culinaryUses: ["Sweets", "Tea", "Biryani", "Baking"],
    category: "barks",
    relatedSlugs: ["cassia"],
    recipeSlugs: ["chai", "kheer"],
    aliases: ["true cinnamon", "cinnamomum verum", "ceylon cinnamon"],
    forms: WP,
    varieties: [{ slug: "cinnamon", name: "Cinnamon Quills" }],
    grades: ["premium", "standard", "export"],
    featured: true,
  }),
  spice({
    id: "cassia",
    slug: "cassia",
    canonicalName: "Cassia",
    commonNames: ["Chinese cassia", "Dalchini (common Indian trade)"],
    indianNames: ["Dalchini"],
    hindiName: "दालचीनी",
    regionalNames: ["Taj"],
    botanicalName: "Cinnamomum cassia",
    botanicalFamily: "Lauraceae",
    shortDescription: "Thicker, stronger bark commonly used as dalchini in Indian savoury cooking.",
    description:
      "Cassia is stronger and less delicate than true cinnamon. Comparison pages should explain the difference rather than treating all dalchini as one botanical species.",
    growingRegions: ["Imported lots and Indian trade channels — verify origin per batch"],
    flavourProfile: "Spicy-sweet, robust",
    aromaProfile: "Strong bark, warming",
    colour: "Dark reddish-brown",
    heatLevel: "none",
    culinaryUses: ["Curry", "Biryani", "Garam masala"],
    category: "barks",
    relatedSlugs: ["cinnamon"],
    recipeSlugs: ["biryani"],
    aliases: ["dalchini", "cassia bark", "cinnamomum cassia", "दालचीनी"],
    forms: WP,
    varieties: [{ slug: "cassia", name: "Cassia Bark" }],
    grades: ["premium", "standard", "export"],
    needsVerification: true,
  }),
];

function chilli(
  slug: string,
  name: string,
  hindi: string,
  region: string,
  heat: HeatLevel,
  aliases: string[],
  extra?: Partial<SpiceEntity>
): SpiceEntity {
  return spice({
    id: slug,
    slug,
    canonicalName: name,
    commonNames: [name, `${name} chilli`],
    indianNames: [name],
    hindiName: hindi,
    regionalNames: [region],
    botanicalName: extra?.botanicalName ?? "Capsicum annuum",
    botanicalFamily: "Solanaceae",
    shortDescription: extra?.shortDescription ?? `${name} is an Indian chilli variety used whole, flaked, or as powder.`,
    description:
      extra?.description ??
      `${name} is a recognised Indian chilli type associated with ${region}. Heat, colour, and skin thickness vary by variety. Forms include whole pods, flakes, crushed chilli, and powder.`,
    growingRegions: [region],
    flavourProfile: extra?.flavourProfile ?? "Chilli heat with variety-specific fruitiness",
    aromaProfile: extra?.aromaProfile ?? "Dried red chilli aroma",
    colour: extra?.colour ?? "Red when dried",
    heatLevel: heat,
    culinaryUses: ["Curry", "Pickle", "Masala", "Tandoori"],
    category: "indian-chillies",
    relatedSlugs: extra?.relatedSlugs ?? ["kashmiri-chilli", "byadgi-chilli", "guntur-sannam"],
    recipeSlugs: ["curry", "pickle"],
    aliases,
    forms: CHILLI,
    varieties: [{ slug, name: `${name}`, region }],
    grades: ["premium", "standard", "export"],
    featured: extra?.featured,
    needsVerification: extra?.needsVerification,
  });
}

export const CHILLI_ENTITIES: SpiceEntity[] = [
  chilli("kashmiri-chilli", "Kashmiri Chilli", "कश्मीरी मिर्च", "Kashmir", "mild", ["kashmiri mirch", "kashmiri chilli powder", "कश्मीरी मिर्च"], {
    featured: true,
    flavourProfile: "Mild heat, vivid colour, gentle fruitiness",
    colour: "Deep crimson",
    botanicalName: "Capsicum annuum",
    description:
      "Kashmiri chilli is valued in Indian cooking for colour more than extreme heat. Compare with Byadgi, which is also used for colour in southern cooking.",
  }),
  chilli("byadgi-chilli", "Byadgi Chilli", "ब्याडगी मिर्च", "Karnataka", "mild", ["bedgi", "byadgi chilli", "byadagi"], {
    featured: true,
    flavourProfile: "Low to moderate heat, rich colour",
    colour: "Wrinkled deep red",
  }),
  chilli("guntur-sannam", "Guntur Sannam", "गुंटूर सन्नम", "Andhra Pradesh", "hot", ["sannam chilli", "guntur chilli", "s4 chilli"]),
  chilli("guntur-teja", "Guntur Teja", "गुंटूर तेजा", "Andhra Pradesh", "very-hot", ["teja chilli", "s17 teja", "guntur teja"]),
  chilli("s4-chilli", "S4 Chilli", "एस4 मिर्च", "Andhra Pradesh", "hot", ["s4 chilli", "sannam s4"]),
  chilli("s10-chilli", "S10 Chilli", "एस10 मिर्च", "Andhra Pradesh", "hot", ["s10 chilli"]),
  chilli("resham-patti", "Resham Patti", "रेशम पट्टी", "Madhya Pradesh", "medium", ["resham patti chilli"]),
  chilli("mathania-chilli", "Mathania Chilli", "मथानिया मिर्च", "Rajasthan", "medium", ["mathania", "mathaniya chilli"]),
  chilli("jwala-chilli", "Jwala Chilli", "ज्वाला मिर्च", "Gujarat", "hot", ["jwala", "jwala pepper"]),
  chilli("sankeshwari-chilli", "Sankeshwari Chilli", "संकेश्वरी मिर्च", "Maharashtra", "hot", ["sankeshwari"]),
  chilli("dhani-chilli", "Dhani Chilli", "धनी मिर्च", "Rajasthan", "hot", ["dhani chilli"]),
  chilli("mundu-chilli", "Mundu Chilli", "मुंडु मिर्च", "Tamil Nadu", "medium", ["ramnad mundu", "round chilli"]),
  chilli("kanthari-chilli", "Kanthari Chilli", "कंथारी", "Kerala", "very-hot", ["kanthari", "bird's eye chilli kerala"], {
    botanicalName: "Capsicum frutescens",
  }),
  chilli("naga-chilli", "Naga Chilli", "नागा मिर्च", "Northeast India", "very-hot", ["naga morich", "naga chilli"], {
    botanicalName: "Capsicum chinense",
  }),
  chilli("bhut-jolokia", "Bhut Jolokia", "भुत जोलोकिया", "Assam", "very-hot", ["ghost pepper", "bhut jolokia"], {
    botanicalName: "Capsicum chinense",
  }),
  chilli("boria-chilli", "Boria Chilli", "बोरिया मिर्च", "Rajasthan", "medium", ["boria chilli"]),
  chilli("ramnad-mundu", "Ramnad Mundu", "रामनाद मुंडु", "Tamil Nadu", "medium", ["ramnad mundu chilli"]),
  chilli("salem-chilli", "Salem Chilli", "सेलम मिर्च", "Tamil Nadu", "hot", ["salem chilli"]),
  chilli("wonder-hot", "Wonder Hot Chilli", "वंडर हॉट", "Andhra Pradesh", "hot", ["wonder hot chilli"]),
  chilli("longi-chilli", "Longi Chilli", "लोंगी मिर्च", "Rajasthan", "medium", ["longi chilli"]),
  chilli("tomato-chilli", "Tomato Chilli", "टमाटर मिर्च", "Karnataka", "mild", ["tomato chilli"]),
  chilli("round-chilli", "Round Chilli", "गोल मिर्च", "Tamil Nadu", "medium", ["round chilli", "gol mirch"]),
];

function simpleSpice(opts: {
  id: string;
  name: string;
  hindi: string;
  botanical: string;
  family: string;
  category: string;
  regions: string[];
  flavour: string;
  aroma: string;
  colour: string;
  heat?: HeatLevel;
  forms?: SpiceForm[];
  aliases: string[];
  related: string[];
  uses: string[];
  featured?: boolean;
  varieties?: SpiceEntity["varieties"];
  grades?: string[];
  sanskrit?: string;
  needsVerification?: boolean;
}): SpiceEntity {
  return spice({
    id: opts.id,
    slug: opts.id,
    canonicalName: opts.name,
    commonNames: [opts.name],
    indianNames: [opts.name],
    hindiName: opts.hindi,
    regionalNames: opts.regions,
    sanskritName: opts.sanskrit,
    botanicalName: opts.botanical,
    botanicalFamily: opts.family,
    shortDescription: `${opts.name} — Indian spice used in ${opts.uses.slice(0, 3).join(", ").toLowerCase()}.`,
    description: `${opts.name} (${opts.botanical}) is used in Indian cooking. Growing regions associated with Indian supply include ${opts.regions.join(", ")}. Product pages list form, grade, and food information separately from this botanical profile.`,
    growingRegions: opts.regions,
    flavourProfile: opts.flavour,
    aromaProfile: opts.aroma,
    colour: opts.colour,
    heatLevel: opts.heat ?? "none",
    culinaryUses: opts.uses,
    category: opts.category,
    relatedSlugs: opts.related,
    recipeSlugs: ["curry"],
    aliases: opts.aliases,
    forms: opts.forms ?? WP,
    varieties: opts.varieties ?? [{ slug: opts.id, name: opts.name }],
    grades: opts.grades ?? ["premium", "standard", "export"],
    featured: opts.featured,
    needsVerification: opts.needsVerification,
  });
}

export const CORE_SPICES: SpiceEntity[] = [
  simpleSpice({
    id: "fennel",
    name: "Fennel Seeds",
    hindi: "सौंफ",
    botanical: "Foeniculum vulgare",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Gujarat", "Rajasthan"],
    flavour: "Sweet, anise-like",
    aroma: "Liquorice-sweet",
    colour: "Green to khaki seeds",
    aliases: ["saunf", "sauf", "fennel", "foeniculum vulgare", "सौंफ"],
    related: ["anise", "star-anise", "cumin"],
    uses: ["After-meal mukhwas", "Sweets", "Vegetables", "Tea"],
  }),
  simpleSpice({
    id: "fenugreek",
    name: "Fenugreek Seeds",
    hindi: "मेथी दाना",
    botanical: "Trigonella foenum-graecum",
    family: "Fabaceae",
    category: "seeds",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    flavour: "Bitter, maple-like when roasted",
    aroma: "Warm, bitter-sweet",
    colour: "Amber-yellow angular seeds",
    aliases: ["methi", "methi dana", "fenugreek", "trigonella foenum-graecum", "मेथी"],
    related: ["mustard", "ajwain"],
    uses: ["Curry", "Pickle", "Kasuri methi blends", "Dal"],
    forms: ["whole", "powder", "roasted"],
    featured: true,
  }),
  simpleSpice({
    id: "mustard",
    name: "Mustard Seeds",
    hindi: "राई",
    botanical: "Brassica juncea",
    family: "Brassicaceae",
    category: "seeds",
    regions: ["Rajasthan", "Gujarat", "Uttar Pradesh"],
    flavour: "Pungent when popped",
    aroma: "Sharp when tempered",
    colour: "Brown or black small round seeds",
    aliases: ["rai", "rai sarson", "mustard seeds", "brassica juncea", "राई", "sarson"],
    related: ["fenugreek", "nigella"],
    uses: ["South Indian tadka", "Pickle", "Fish curry"],
    forms: SEED,
    varieties: [
      { slug: "brown-mustard", name: "Brown Mustard Seeds" },
      { slug: "black-mustard", name: "Black Mustard Seeds" },
    ],
  }),
  simpleSpice({
    id: "nigella",
    name: "Nigella Seeds",
    hindi: "कलौंजी",
    botanical: "Nigella sativa",
    family: "Ranunculaceae",
    category: "seeds",
    regions: ["Rajasthan", "Uttar Pradesh"],
    flavour: "Oregano-onion, slightly bitter",
    aroma: "Peppery",
    colour: "Matte black teardrop seeds",
    aliases: ["kalonji", "kalonji seeds", "nigella", "nigella sativa", "कलौंजी"],
    related: ["black-cumin", "mustard"],
    uses: ["Naan topping", "Pickle", "Vegetables"],
    forms: SEED,
  }),
  simpleSpice({
    id: "ajwain",
    name: "Ajwain",
    hindi: "अजवाइन",
    botanical: "Trachyspermum ammi",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Rajasthan", "Gujarat"],
    flavour: "Thyme-like, pungent",
    aroma: "Strong thymol",
    colour: "Small grey-brown seeds",
    aliases: ["carom", "carom seeds", "ajwain", "trachyspermum ammi", "अजवाइन"],
    related: ["cumin", "fennel"],
    uses: ["Paratha", "Lentils", "Snacks", "Fish"],
    forms: SEED,
  }),
  simpleSpice({
    id: "star-anise",
    name: "Star Anise",
    hindi: "चक्र फूल",
    botanical: "Illicium verum",
    family: "Schisandraceae",
    category: "whole-spices",
    regions: ["Northeast India", "Imported lots — verify origin"],
    flavour: "Liquorice, sweet-spicy",
    aroma: "Anise-strong",
    colour: "Rust-red star pods",
    aliases: ["chakri phool", "star anise", "illicium verum"],
    related: ["fennel", "anise"],
    uses: ["Biryani", "Phirni", "Chinese-Indian gravies"],
    forms: WP,
    needsVerification: true,
  }),
  simpleSpice({
    id: "bay-leaf",
    name: "Indian Bay Leaf",
    hindi: "तेज पत्ता",
    botanical: "Cinnamomum tamala",
    family: "Lauraceae",
    category: "herbs",
    regions: ["Northeast India", "Himalayan foothills"],
    flavour: "Clove-cinnamon leaf",
    aroma: "Warm, cassia-like",
    colour: "Olive dried leaves",
    aliases: ["tej patta", "indian bay leaf", "cinnamomum tamala", "तेज पत्ता"],
    related: ["cassia", "cinnamon"],
    uses: ["Pulao", "Curry", "Garam masala"],
    forms: ["leaves"],
  }),
  simpleSpice({
    id: "mace",
    name: "Mace",
    hindi: "जावित्री",
    botanical: "Myristica fragrans",
    family: "Myristicaceae",
    category: "premium-spices",
    regions: ["Kerala"],
    flavour: "Finer, sharper than nutmeg",
    aroma: "Warm, peppery-sweet",
    colour: "Orange-red aril",
    aliases: ["javitri", "mace", "myristica fragrans", "जावित्री"],
    related: ["nutmeg"],
    uses: ["Biryani", "Korma", "Baking", "Garam masala"],
    forms: ["whole", "powder"],
    featured: true,
  }),
  simpleSpice({
    id: "nutmeg",
    name: "Nutmeg",
    hindi: "जायफल",
    botanical: "Myristica fragrans",
    family: "Myristicaceae",
    category: "premium-spices",
    regions: ["Kerala"],
    flavour: "Warm, sweet-spicy",
    aroma: "Rich, woody-sweet",
    colour: "Brown oval seed",
    aliases: ["jaiphal", "nutmeg", "myristica fragrans", "जायफल"],
    related: ["mace"],
    uses: ["Sweets", "Bechamel-style gravies", "Garam masala", "Baking"],
    forms: WP,
    featured: true,
  }),
  simpleSpice({
    id: "saffron",
    name: "Saffron",
    hindi: "केसर",
    botanical: "Crocus sativus",
    family: "Iridaceae",
    category: "premium-spices",
    regions: ["Kashmir"],
    flavour: "Honey, hay, bitter-floral",
    aroma: "Distinct hay-honey",
    colour: "Deep crimson stigmas",
    aliases: ["kesar", "zafran", "kashmir saffron", "crocus sativus", "केसर"],
    related: ["green-cardamom"],
    uses: ["Biryani", "Kheer", "Tea", "Sweets"],
    forms: ["threads"],
    featured: true,
    grades: ["premium"],
  }),
  simpleSpice({
    id: "long-pepper",
    name: "Long Pepper",
    hindi: "पिप्पली",
    botanical: "Piper longum",
    family: "Piperaceae",
    category: "whole-spices",
    regions: ["Kerala", "Northeast India", "Madhya Pradesh"],
    flavour: "Hotter, sweeter than black pepper",
    aroma: "Earthy pepper",
    colour: "Grey-brown catkins",
    heat: "medium",
    aliases: ["pippali", "pipli", "long pepper", "piper longum"],
    related: ["black-pepper", "cubeb"],
    uses: ["Rasam", "Traditional spice mixes", "Pickle"],
    forms: WP,
  }),
  simpleSpice({
    id: "cubeb",
    name: "Cubeb",
    hindi: "कबाब चीनी",
    botanical: "Piper cubeba",
    family: "Piperaceae",
    category: "whole-spices",
    regions: ["Imported lots — verify origin"],
    flavour: "Pepper with allspice notes",
    aroma: "Camphor-pepper",
    colour: "Tailed peppercorns",
    heat: "medium",
    aliases: ["kabab chini", "cubeb pepper", "piper cubeba"],
    related: ["black-pepper", "long-pepper"],
    uses: ["Mughlai spice mixes", "Meat"],
    forms: WP,
    needsVerification: true,
  }),
  simpleSpice({
    id: "dill-seed",
    name: "Dill Seeds",
    hindi: "सोआ",
    botanical: "Anethum graveolens",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Rajasthan", "Gujarat"],
    flavour: "Grassy, caraway-adjacent",
    aroma: "Fresh-herbal",
    colour: "Flat brown seeds",
    aliases: ["suva", "soa", "dill seeds", "anethum graveolens"],
    related: ["caraway", "fennel"],
    uses: ["Vegetables", "Raita", "Lentils"],
    forms: SEED,
  }),
  simpleSpice({
    id: "celery-seed",
    name: "Celery Seeds",
    hindi: "अजमोदा",
    botanical: "Apium graveolens",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Punjab", "Haryana"],
    flavour: "Bitter-celery",
    aroma: "Savoury",
    colour: "Tiny brown seeds",
    aliases: ["celery seeds", "ajmoda", "apium graveolens"],
    related: ["ajwain", "dill-seed"],
    uses: ["Pickle", "Spice blends"],
    forms: SEED,
  }),
  simpleSpice({
    id: "poppy-seed",
    name: "White Poppy Seeds",
    hindi: "खसखस",
    botanical: "Papaver somniferum",
    family: "Papaveraceae",
    category: "seeds",
    regions: ["Madhya Pradesh", "Rajasthan", "Uttar Pradesh"],
    flavour: "Nutty, creamy when ground",
    aroma: "Mild, nutty",
    colour: "Off-white",
    aliases: ["khus khus", "posto", "white poppy", "papaver somniferum", "खसखस"],
    related: ["sesame"],
    uses: ["Bengali posto", "Korma thickening", "Sweets"],
    forms: SEED,
  }),
  simpleSpice({
    id: "sesame",
    name: "Sesame Seeds",
    hindi: "तिल",
    botanical: "Sesamum indicum",
    family: "Pedaliaceae",
    category: "seeds",
    regions: ["Gujarat", "Rajasthan", "Madhya Pradesh"],
    flavour: "Nutty",
    aroma: "Toasted when roasted",
    colour: "White, brown, or black",
    aliases: ["til", "sesame", "sesamum indicum", "तिल"],
    related: ["poppy-seed", "mustard"],
    uses: ["Laddoo", "Chikki", "Temper", "Chutney"],
    forms: ["whole", "roasted"],
    varieties: [
      { slug: "white-sesame", name: "White Sesame Seeds" },
      { slug: "black-sesame", name: "Black Sesame Seeds" },
    ],
  }),
  simpleSpice({
    id: "anise",
    name: "Anise Seeds",
    hindi: "अनीस",
    botanical: "Pimpinella anisum",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Imported lots and limited Indian cultivation — verify origin"],
    flavour: "Sweet anise",
    aroma: "Liquorice",
    colour: "Grey-green seeds",
    aliases: ["aniseed", "pimpinella anisum"],
    related: ["fennel", "star-anise"],
    uses: ["Sweets", "Digestive mixes"],
    forms: SEED,
    needsVerification: true,
  }),
  simpleSpice({
    id: "caraway",
    name: "Caraway",
    hindi: "विलायती जीरा",
    botanical: "Carum carvi",
    family: "Apiaceae",
    category: "seeds",
    regions: ["Temperate production — verify origin per lot"],
    flavour: "Rye-bread, sharper than cumin",
    aroma: "Fresh-spicy",
    colour: "Curved brown seeds",
    aliases: ["caraway seeds", "carum carvi", "persian cumin"],
    related: ["cumin", "black-cumin", "fennel"],
    uses: ["Breads", "Cabbage dishes", "Comparison with cumin"],
    forms: SEED,
    featured: true,
  }),
  simpleSpice({
    id: "kokum",
    name: "Kokum",
    hindi: "कोकम",
    botanical: "Garcinia indica",
    family: "Clusiaceae",
    category: "speciality-spices",
    regions: ["Maharashtra", "Goa", "Karnataka", "Kerala"],
    flavour: "Sour, fruity",
    aroma: "Tamarind-adjacent, darker",
    colour: "Dark purple-black rinds",
    aliases: ["cocum", "garcinia indica", "amsul"],
    related: ["tamarind", "amchur"],
    uses: ["Malvani curry", "Solkadhi", "Fish curry"],
    forms: ["whole"],
  }),
  simpleSpice({
    id: "tamarind",
    name: "Tamarind",
    hindi: "इमली",
    botanical: "Tamarindus indica",
    family: "Fabaceae",
    category: "speciality-spices",
    regions: ["Andhra Pradesh", "Tamil Nadu", "Karnataka", "Maharashtra"],
    flavour: "Sour-sweet",
    aroma: "Fruity sour",
    colour: "Dark brown pulp",
    aliases: ["imli", "tamarindus indica", "इमली"],
    related: ["kokum", "amchur"],
    uses: ["Sambar", "Rasam", "Chutney", "Puliyodarai"],
    forms: ["whole", "powder"],
  }),
  simpleSpice({
    id: "curry-leaf",
    name: "Dried Curry Leaves",
    hindi: "कड़ी पत्ता",
    botanical: "Murraya koenigii",
    family: "Rutaceae",
    category: "herbs",
    regions: ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh"],
    flavour: "Citrus-herbal, nutty when fried",
    aroma: "Distinct curry-leaf",
    colour: "Olive dried leaflets",
    aliases: ["kadi patta", "karuveppilai", "murraya koenigii", "कड़ी पत्ता"],
    related: ["mustard", "asafoetida"],
    uses: ["South Indian tadka", "Rasam", "Chutney"],
    forms: ["leaves"],
  }),
  simpleSpice({
    id: "dried-mint",
    name: "Dried Mint",
    hindi: "पुदीना",
    botanical: "Mentha spicata",
    family: "Lamiaceae",
    category: "herbs",
    regions: ["Uttar Pradesh", "Punjab", "Rajasthan"],
    flavour: "Cool, green",
    aroma: "Menthol",
    colour: "Green crumbled leaves",
    aliases: ["pudina", "dried mint", "mentha"],
    related: ["dried-fenugreek-leaves"],
    uses: ["Raita", "Chaat", "Chutney", "Tea"],
    forms: ["leaves"],
  }),
  simpleSpice({
    id: "kasuri-methi",
    name: "Dried Fenugreek Leaves",
    hindi: "कसूरी मेथी",
    botanical: "Trigonella foenum-graecum",
    family: "Fabaceae",
    category: "herbs",
    regions: ["Rajasthan", "Gujarat", "Madhya Pradesh"],
    flavour: "Bitter-savoury, maple",
    aroma: "Strong methi leaf",
    colour: "Olive crumbled leaves",
    aliases: ["kasuri methi", "kasoori methi", "dried fenugreek leaves"],
    related: ["fenugreek"],
    uses: ["Butter chicken-style gravies", "Naan", "Vegetables"],
    forms: ["leaves"],
    featured: true,
  }),
  simpleSpice({
    id: "ginger",
    name: "Dried Ginger",
    hindi: "सौंठ",
    botanical: "Zingiber officinale",
    family: "Zingiberaceae",
    category: "roots",
    regions: ["Kerala", "Meghalaya", "Karnataka", "Odisha"],
    flavour: "Hot, lemony-woody",
    aroma: "Pungent ginger",
    colour: "Ivory to beige slices or powder",
    heat: "mild",
    aliases: ["sonth", "saunth", "dried ginger", "zingiber officinale", "सौंठ"],
    related: ["turmeric", "galangal"],
    uses: ["Tea masala", "Sweets", "Curry"],
    forms: ["root", "powder"],
  }),
  simpleSpice({
    id: "galangal",
    name: "Dried Galangal",
    hindi: "कुलंजन",
    botanical: "Alpinia galanga",
    family: "Zingiberaceae",
    category: "roots",
    regions: ["Northeast India", "Kerala"],
    flavour: "Pine-citrus, sharper than ginger",
    aroma: "Camphor-ginger",
    colour: "Pale dried slices",
    aliases: ["kulanjan", "galangal", "alpinia galanga"],
    related: ["ginger", "turmeric"],
    uses: ["Regional spice mixes", "Comparison with ginger"],
    forms: ["root", "powder"],
  }),
  simpleSpice({
    id: "asafoetida",
    name: "Asafoetida",
    hindi: "हींग",
    botanical: "Ferula assa-foetida",
    family: "Apiaceae",
    category: "speciality-spices",
    regions: ["Imported resin compounded in India — verify composition"],
    flavour: "Alliaceous, savoury",
    aroma: "Pungent sulphur when raw; mellow in ghee",
    colour: "Cream to yellow compounded powder",
    aliases: ["hing", "heeng", "asafoetida", "हींग"],
    related: ["cumin", "turmeric"],
    uses: ["Dal tadka", "Sambar", "Jain cooking"],
    forms: ["powder"],
    featured: true,
  }),
  simpleSpice({
    id: "amchur",
    name: "Amchur",
    hindi: "अमचूर",
    botanical: "Mangifera indica",
    family: "Anacardiaceae",
    category: "speciality-spices",
    regions: ["Uttar Pradesh", "Bihar", "Andhra Pradesh"],
    flavour: "Tart, fruity",
    aroma: "Dried mango",
    colour: "Beige powder",
    aliases: ["amchoor", "dry mango powder", "अमचूर"],
    related: ["tamarind", "kokum"],
    uses: ["Chaat", "Vegetables", "Chole"],
    forms: ["powder"],
  }),
  simpleSpice({
    id: "dried-garlic",
    name: "Dried Garlic",
    hindi: "सूखा लहसुन",
    botanical: "Allium sativum",
    family: "Amaryllidaceae",
    category: "speciality-spices",
    regions: ["Madhya Pradesh", "Rajasthan", "Gujarat"],
    flavour: "Concentrated garlic",
    aroma: "Pungent",
    colour: "Cream flakes or powder",
    aliases: ["garlic flakes", "garlic powder", "allium sativum"],
    related: ["dried-ginger", "asafoetida"],
    uses: ["Masala blends", "Marinades"],
    forms: ["flakes", "powder"],
  }),
  simpleSpice({
    id: "white-pepper",
    name: "White Pepper",
    hindi: "सफेद मिर्च",
    botanical: "Piper nigrum",
    family: "Piperaceae",
    category: "whole-spices",
    regions: ["Kerala", "Karnataka"],
    flavour: "Earthy heat, less floral than black pepper",
    aroma: "Musty-pungent",
    colour: "Cream berries",
    heat: "medium",
    aliases: ["safed mirch", "white peppercorns", "piper nigrum white"],
    related: ["black-pepper"],
    uses: ["Light sauces", "Soups", "Some meat dishes"],
    forms: WP,
  }),
];

function masala(id: string, name: string, hindi: string, aliases: string[], regions: string[], related: string[]): SpiceEntity {
  return spice({
    id,
    slug: id,
    canonicalName: name,
    commonNames: [name],
    indianNames: [name],
    hindiName: hindi,
    regionalNames: regions,
    botanicalName: "Blend (multiple spices)",
    botanicalFamily: "n/a",
    shortDescription: `${name} is an Indian spice blend. Ingredient lists on packs are the legal composition.`,
    description: `${name} is a prepared Indian masala. Recipes vary by producer. SpicyCorner lists typical culinary use only. Allergen and ingredient declarations on the pack / product record are authoritative.`,
    growingRegions: regions,
    flavourProfile: "House blend — see product ingredients",
    aromaProfile: "Roasted spice blend",
    colour: "Varies by recipe",
    heatLevel: "medium",
    culinaryUses: ["Curry", "Marinade", "Regional cooking"],
    category: "masalas",
    relatedSlugs: related,
    recipeSlugs: [id.replace(/-masala$/, "")],
    aliases,
    forms: BLEND,
    varieties: [{ slug: id, name }],
    grades: ["premium", "standard", "export"],
  });
}

export const MASALA_ENTITIES: SpiceEntity[] = [
  masala("garam-masala", "Garam Masala", "गरम मसाला", ["garam masala"], ["North India"], ["cumin", "coriander", "green-cardamom", "clove"]),
  masala("chaat-masala", "Chaat Masala", "चाट मसाला", ["chat masala", "chaat masala"], ["North India"], ["amchur", "cumin"]),
  masala("biryani-masala", "Biryani Masala", "बिरयानी मसाला", ["biryani masala"], ["Hyderabad", "Lucknow", "Kerala"], ["green-cardamom", "mace", "black-cumin"]),
  masala("tandoori-masala", "Tandoori Masala", "तंदूरी मसाला", ["tandoori masala"], ["Punjab"], ["kashmiri-chilli", "cumin", "coriander"]),
  masala("chicken-masala", "Chicken Masala", "चिकन मसाला", ["chicken masala"], ["North India"], ["garam-masala", "kashmiri-chilli"]),
  masala("meat-masala", "Meat Masala", "मीट मसाला", ["meat masala", "mutton masala"], ["North India"], ["black-cardamom", "clove"]),
  masala("fish-masala", "Fish Masala", "फिश मसाला", ["fish masala"], ["Goa", "Kerala", "Bengal"], ["kokum", "mustard", "tamarind"]),
  masala("curry-masala", "Curry Masala", "करी मसाला", ["curry masala", "curry powder"], ["South India", "UK trade blends"], ["coriander", "turmeric", "cumin"]),
  masala("kitchen-king", "Kitchen King Masala", "किचन किंग", ["kitchen king"], ["North India"], ["garam-masala"]),
  masala("chole-masala", "Chole Masala", " छोले मसाला", ["chole masala", "chana masala"], ["Punjab"], ["amchur", "cumin", "coriander"]),
  masala("rajma-masala", "Rajma Masala", "राजमा मसाला", ["rajma masala"], ["North India"], ["cumin", "coriander"]),
  masala("pav-bhaji-masala", "Pav Bhaji Masala", "पाव भाजी मसाला", ["pav bhaji masala"], ["Maharashtra"], ["fennel", "amchur"]),
  masala("sambar-masala", "Sambar Masala", "सांबर मसाला", ["sambar powder", "sambar masala"], ["Tamil Nadu", "Karnataka", "Kerala"], ["coriander", "fenugreek", "curry-leaf"]),
  masala("rasam-powder", "Rasam Powder", "रसम पाउडर", ["rasam podi"], ["Tamil Nadu", "Karnataka"], ["black-pepper", "cumin", "tamarind"]),
  masala("madras-curry-powder", "Madras Curry Powder", "मद्रास करी पाउडर", ["madras curry powder"], ["Tamil Nadu"], ["coriander", "turmeric", "kashmiri-chilli"]),
  masala("vindaloo-masala", "Vindaloo Masala", "विंदालू मसाला", ["vindaloo masala"], ["Goa"], ["kashmiri-chilli", "cumin", "mustard"]),
  masala("korma-masala", "Korma Masala", "कोरमा मसाला", ["korma masala"], ["North India", "Hyderabad"], ["green-cardamom", "white-pepper", "poppy-seed"]),
  masala("butter-chicken-masala", "Butter Chicken Masala", "बटर चिकन मसाला", ["butter chicken masala", "murgh makhani masala"], ["Punjab", "Delhi"], ["kashmiri-chilli", "kasuri-methi"]),
  masala("tikka-masala", "Tikka Masala", "टिक्का मसाला", ["tikka masala"], ["Punjab", "UK-Indian restaurants"], ["tandoori-masala", "kashmiri-chilli"]),
  masala("chettinad-masala", "Chettinad Masala", "चेट्टिनाड मसाला", ["chettinad masala"], ["Tamil Nadu"], ["black-pepper", "fennel", "star-anise"]),
  masala("goda-masala", "Goda Masala", "गोडा मसाला", ["goda masala"], ["Maharashtra"], ["sesame", "coriander"]),
  masala("kolhapuri-masala", "Kolhapuri Masala", "कोल्हापुरी मसाला", ["kolhapuri masala"], ["Maharashtra"], ["guntur-teja", "sesame"]),
  masala("malvani-masala", "Malvani Masala", "मालवणी मसाला", ["malvani masala"], ["Maharashtra"], ["kokum", "black-pepper"]),
  masala("panch-phoron", "Panch Phoron", "पंच फोरन", ["panch phoron", "panch phoran", "five spice bengal"], ["West Bengal", "Odisha", "Assam"], ["mustard", "fenugreek", "nigella", "fennel", "cumin"]),
  masala("pickle-masala", "Pickle Masala", "अचार मसाला", ["achar masala", "pickle masala"], ["Rajasthan", "Gujarat", "Punjab"], ["mustard", "fenugreek", "fennel"]),
  masala("tea-masala", "Tea Masala", "चाय मसाला", ["chai masala", "tea masala"], ["North India"], ["green-cardamom", "ginger", "cinnamon", "clove"]),
  masala("dabeli-masala", "Dabeli Masala", "दबेली मसाला", ["dabeli masala"], ["Gujarat"], ["fennel", "cumin"]),
  masala("misal-masala", "Misal Masala", "मिसळ मसाला", ["misal masala"], ["Maharashtra"], ["kolhapuri-masala"]),
  masala("idli-podi", "Idli Podi", "इडली पोड़ी", ["gunpowder", "idli podi", "molaga podi"], ["Tamil Nadu", "Andhra Pradesh"], ["sesame", "kashmiri-chilli"]),
];

export const ALL_SPICE_ENTITIES: SpiceEntity[] = [
  ...SPICE_ENTITIES,
  ...CHILLI_ENTITIES,
  ...CORE_SPICES,
  ...MASALA_ENTITIES,
];

export function getSpiceBySlug(slug: string): SpiceEntity | undefined {
  return ALL_SPICE_ENTITIES.find((s) => s.slug === slug);
}
